export enum ApikitErrorCode {
    APIKIT_ZOD_SCHEMA_INVALID = "APIKIT_ZOD_SCHEMA_INVALID",
    APIKIT_UNKNOWN_ERROR = "APIKIT_UNKNOWN_ERROR",
    APIKIT_MISSING_RESPONSE_DATA_AXIOS = "APIKIT_MISSING_RESPONSE_DATA_AXIOS",
    APIKIT_INVALID_ERROR_CONTRACT = "APIKIT_INVALID_ERROR_CONTRACT",
    APIKIT_UNKNOWN_ERROR_RESPONSE = "APIKIT_UNKNOWN_ERROR_RESPONSE",
    APIKIT_AXIOS_NETWORK_UNKNOWN_ERROR = "APIKIT_AXIOS_NETWORK_UNKNOWN_ERROR",

    APIKIT_UNKNOWN_CODE_ERROR = "APIKIT_UNKNOWN_CODE_ERROR",

    APIKIT_RESPONSE_INVALID = "APIKIT_RESPONSE_INVALID",
    APIKIT_ERROR_MALFORMED = "APIKIT_ERROR_MALFORMED",
    APIKIT_DATA_MISSING = "APIKIT_DATA_MISSING",
}