export enum ApikitAxiosErrorCode {
    // NETWORK
    APIKIT_AXIOS_ERR_NETWORK ="APIKIT_AXIOS_ERR_NETWORK",
    APIKIT_AXIOS_ECONNREFUSED = "APIKIT_AXIOS_ECONNREFUSED",
    APIKIT_AXIOS_ECONNABORTED = "APIKIT_AXIOS_ECONNABORTED",

    // CLIENT CONTROL
    APIKIT_AXIOS_ERR_CANCELED = "APIKIT_AXIOS_ERR_CANCELED",
    APIKIT_AXIOS_ERR_INVALID_URL="APIKIT_AXIOS_ERR_INVALID_URL",


    // CONFIG / SDK USAGE
    APIKIT_AXIOS_ERR_BAD_REQUEST="APIKIT_AXIOS_ERR_BAD_REQUEST",
    APIKIT_AXIOS_ERR_BAD_RESPONSE="APIKIT_AXIOS_ERR_BAD_RESPONSE",

    // HTTP / SERVER RESPONSE
    APIKIT_AXIOS_ERR_FR_TOO_MANY_REDIRECTS="APIKIT_AXIOS_ERR_FR_TOO_MANY_REDIRECTS",
    APIKIT_AXIOS_ERR_NOT_SUPPORT="APIKIT_AXIOS_ERR_NOT_SUPPORT",
    APIKIT_AXIOS_ERR_DEPRECATED="APIKIT_AXIOS_ERR_DEPRECATED",
    APIKIT_AXIOS_ETIMEDOUT="APIKIT_AXIOS_ETIMEDOUT",
    APIKIT_AXIOS_ERR_BAD_OPTION="APIKIT_AXIOS_ERR_BAD_OPTION",
    APIKIT_AXIOS_ERR_BAD_OPTION_VALUE="APIKIT_AXIOS_ERR_BAD_OPTION_VALUE",
    APIKIT_AXIOS_ERR_FORM_DATA_DEPTH_EXCEEDED="APIKIT_AXIOS_ERR_FORM_DATA_DEPTH_EXCEEDED",
}